name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Build and publish
        uses: JRubics/poetry-publish@v2.0
        with:
          poetry_install_options: --without dev,test
          pypi_token: ${{ secrets.PYPI_TOKEN }}
